/** The question each term's click-through demo answers; it is also the demo's heading. */
export const vibeCodingLabTitles: Record<string, string> = {
	'confidence-interval': '同样是 70%，测多少题有区别吗？',
	component: '一个按钮组件，怎样复用出整个页面？',
	state: '点一下按钮，状态经历了什么？',
	props: '同一个按钮，怎么被传成不同样子？',
	'responsive-design': '拖一拖屏宽，页面怎么变？',
	dom: '改一个节点，页面哪里会动？',
	hydration: '同一个按钮，水合前后差在哪？',
	api: '调一次天气 API，会发生什么？',
	endpoint: '一个地址，怎么装下查和建？',
	runtime: '同一行代码，插在哪个运行时上？',
	middleware: '一个请求，要过几道公用的关？',
	authentication: '登录之后，系统凭什么一直认得你？',
	'environment-variable': '一份代码，怎么在两个环境各连各的库？',
	event: '点一下按钮，谁在听？',
	routing: '换一个地址，会打开哪一页？',
	ssr: 'CSR 和 SSR，首屏差在哪？',
	'browser-storage': '存一条数据，刷新后还在吗？',
	prompt: '同一个愿望，怎么说才不跑偏？',
	'zero-shot': '一个例子都不给，AI 能做对吗？',
	'few-shot': '给三个例子，AI 就会照着做吗？',
	frontend: '一个页面是怎样做出来的？',
	backend: '一次请求会经过哪些部分？',
	agent: 'Model 和 Harness，怎样搭档完成任务？',
	'vibe-coding': '同样的需求，一口气说完还是一轮轮调？',
	'context-window': '聊到第 60 轮，开头的约定还在吗？',
	token: '「帮我总结这份报告」发出去，模型收到的是什么？',
	harness: '模型说「删了它」，框架照做吗？',
	mcp: '接入一个工单系统，要写几遍代码？',
	skill: '每周都要发的周报，怎么不用每次重新教？',
	rag: '模型没学过的问题，怎么答对？',
	database: '重启服务器，注册的用户还在吗？',
	schema: '同一批数据，为什么有结构才算得动？',
	migration: 'users 表要加一列，怎么改才不出事故？',
	cache: '同一个榜单被打开一万次，都要现算吗？',
	'vector-database': '换个说法提问，库里的答案还找得到吗？',
	git: '让 AI 大改代码之前，你的退路在哪？',
	diff: 'AI 说「只改了按钮」，事实是吗？',
	commit: '一天的修改，怎么提交才不给自己埋雷？',
	branch: 'AI 重构到一半，线上要修急 bug，怎么办？',
	worktree: '你和 Agent 同时要改代码，一个目录够用吗？',
	fork: '别人的仓库你没有写权限，想改怎么办？',
	'pull-request': 'AI 的大改动，直接进主线还是先过评审？',
	checkpoint: '让 Agent 连干三小时，你最多会亏掉多少？',
	build: '写好的代码，怎么变成线上能跑的东西？',
	'ci-cd': '每次发布五道工序，漏一步就出事，怎么办？',
	serverless: '一个小工具要上线，服务器谁来操心？',
	'edge-runtime': '同一个网站，东京用户为什么慢出两秒？',
	observability: '凌晨两点支付挂了，你什么时候能知道？',
	'ai-agent': 'AI 工具怎样把目标变成结果？',
	'data-storage': '一杯拿铁的订单，怎样被存进去、又取回来？',
	'engineering-workflow': 'AI 修了一个登录 bug，这笔改动怎样安全进入主线？',
	'deployment-runtime': '一个作品集网站，怎样从你的电脑走到线上？',
};

export function vibeCodingLabTitle(
	concept: { id: string; categoryId: string },
	fallback: string,
): string {
	return vibeCodingLabTitles[concept.id] ?? vibeCodingLabTitles[concept.categoryId] ?? fallback;
}
